config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :charges
  resources :subscribers
  resources :users
  resources :wikis do
    resources :collaborators, only: [:index, :create, :destroy]
  end

  root 'wikis#index'
end

app/models/charge.rb
class Charge < ActiveRecord::Base
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :wikis
  has_many :collaborators
  has_many :wikis, through: :collaborators

  attr_accessor :role

  enum role: [:standard, :premium, :admin]

  def collaborators
    Collaborator.where(user_id: id)
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  has_many :collaborators
  has_many :users, through: :collaborators

  def collaborator_for(user)
    collaborators.where(user_id: user.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!

  # GET /charges/new
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Wikibed Monthly Subscription \n#{current_user.email}",
      amount: 9_99
    }
  end

  # POST /charges
  # POST /charges.json
  def create
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    subscription = customer.subscriptions.create(plan: "1021")

    current_user.stripeid = customer.id
    current_user.stripesubscriptionid = subscription.id
    current_user.subscribed = true
    current_user.premium!
    current_user.save!

    flash[:notice] = "Thanks for subscribing, #{current_user.email}!"
    redirect_to wikis_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    customer = Stripe::Customer.retrieve(current_user.stripeid)
    subscription = customer.subscriptions.retrieve(current_user.stripesubscriptionid)

    if subscription
      customer.subscriptions.retrieve(subscription.id).delete
      current_user.stripeid = customer.id
      current_user.stripesubscriptionid = nil
      current_user.subscribed = false
      current_user.standard!
      current_user.save!

      flash[:notice] = "You have unsubscribed, #{current_user.email}!"
      redirect_to wikis_path
    else
      flash[:notice] = "You do not have any active subscriptions."
      redirect_to wikis_path
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.require(:charge).permit(:customer, :amount, :description, :currency)
    end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki
  def index
    @users = User.all
  end

  def create
    @collaborator = @wiki.collaborators.new(user_id: params[:user_id])

    if @collaborator.save
      flash[:notice] = "Collaborator was added."
    else
      flash[:error] = "There was a problem adding the collaborator. Try again."
    end

    redirect_to wiki_collaborators_path(@wiki)
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator was removed."
    else
      flash[:error] = "There was a problem removing the collaborator. Try again."
    end

    redirect_to wiki_collaborators_path(@wiki)
  end

  private
  def set_wiki # Sets the wiki in context
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def update

    token = params[:stripeToken]

    customer = Stripe::Customer.create(
      card: token,
      email: current_user.email,
      plan: 1021
    )

    current_user.subscribed = true
    current_user.stripeid = customer.id
    current_user.premium!
    current_user.save!

    flash[:notice] = "Thanks for subscribing, #{current_user.name}!"
    redirect_to wikis_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_subscribers_path
  end
end
#

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]

  # GET /wikis
  # GET /wikis.json
  def index
    @wikis = Wiki.order("title").paginate(:page => params[:page], :per_page => 6)
  end

  # GET /wikis/1
  # GET /wikis/1.json
  def show
    @wikis = Wiki.find(params[:id])
  end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
  end

  # GET /wikis/1/edit
  def edit
  end

  # POST /wikis
  # POST /wikis.json
  def create
    # Assign the current user to the wiki on creation
    @wiki = current_user.wikis.new(wiki_params)

    respond_to do |format|
      if @wiki.save
        format.html { redirect_to @wiki, notice: 'Wiki was successfully created.' }
        format.json { render :show, status: :created, location: @wiki }
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wikis/1
  # PATCH/PUT /wikis/1.json
  def update
    set_wiki
    authorize @wiki

    respond_to do |format|
      if @wiki.update(wiki_params)
        format.html { redirect_to @wiki, notice: 'Wiki was successfully updated.' }
        format.json { render :show, status: :ok, location: @wiki }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wikis/1
  # DELETE /wikis/1.json
  def destroy
    @wikis = policy_scope(Wiki)
    @wiki.destroy
    respond_to do |format|
      format.html { redirect_to wikis_url, notice: 'Wiki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/edit.html.erb
<h1>Editing Charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
  <h4>Upgrade my subscription</h4>
  <p>$9.99 per month, cancel at any time.</p>

    <%= form_tag charges_path, method: :create do %>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="Monthly" data-email="<%= current_user.email %>" data-name="Wikibed Premium"  data-panel-label="Subscribe" data-amount="999" data-locale="auto" data-allow-remember-me=false></script>
    <% end %>
 <% end %>

app/views/collaborators/index.html.erb
<h1>Collaborators for <%= @wiki.title %></h1>

<table class="table">
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td>
        <% if @wiki.users.include?(user) %>
          <%= link_to "Remove as collaborator", wiki_collaborator_path(@wiki, @wiki.collaborator_for(user)), method: :delete, class: "btn btn-danger" %>
        <% else %>
          <%= link_to "Add as collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: "btn btn-success" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikibed</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Wikibed", root_path, :class => 'navbar-brand' %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path, :class => 'navbar-link' %></li>
          <li><a href="http://www.joshuazapata.com">Contact</a></li>
          <% if user_signed_in? %>
          <div class="user-info">
            <% if current_user.subscribed? %>
              <li><%= link_to "Premium", edit_user_registration_path, :class => 'navbar-link' %></li>
            <% else %>
              <li><%= link_to "Unlock Premium Features", new_charge_path, :class => 'navbar-link' %></li>
            <% end %>
              <li><%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %></li>
            <% end %>
          </div>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
  <div class="flash">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

  <%= yield %>
  <a href="#" class="back-to-top"></a>
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

app/views/subscribers/_form.html.erb
<%= form_tag subscriber_path(1), method: :put do %>

<script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="Monthly subscription" data-amount="9_99"></script><span>$9.99 per month, cancel at any time.</span>

<% end %>

app/views/subscribers/new.html.erb
<div class="flex-container">
  <div class="flex-item">
    <h4>Sign up for premium</h4>
    <%= render 'form' %>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>

      <ul>
      <% @wiki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :private %><br>
    <%= f.check_box :private %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wikis/_wiki.html.erb
<div id="hex1" class="hexagon-wrapper">
  <div id="color1" class="hexagon">
    <div class="hexagon-content">
      <h2><%= link_to truncate(wiki.title, length: 27), wiki %></h2>
      <p><%= truncate(wiki.body, length: 90) %></p>
      <p>Created by <em><%= truncate(wiki.user.email, length: 9) %></em></p>
    </div>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Editing Wiki</h1>

<%= render 'form' %>

<%= link_to 'Manage Collaborators', wiki_collaborators_path(@wiki) %>

<%= link_to 'Show', @wiki %> |
<%= link_to 'Back', wikis_path %>

app/views/wikis/index.html.erb
<div class="flex-container">
  <div class="flex-item">
    <button type="button" class="btn btn-lg btn-primary"><%= link_to 'Create your own private or public wiki', new_wiki_path %></button>
  </div>
</div>

<div class="container">
  <div id="wikis">
    <%= render @wikis %>
  </div>
</div>

<div class="container">
  <h3><%= will_paginate @wikis, previous_label: h("<"), next_label: h(">") %></h3>
</div>

app/views/wikis/index.js.erb
$('#wikis').append('<%= j render(@wikis) %>');
<% if @wikis.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@wikis) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 0.5 %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render 'form' %>

<%= link_to 'Back', wikis_path %>

app/views/wikis/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @wiki.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= markdown @wiki.body %>
</p>

<p>
  <strong>Private:</strong>
  <%= @wiki.private %>
</p>

<p>
  <strong>User:</strong>
  <%= @wiki.user %>
</p>

<%= link_to 'Edit', edit_wiki_path(@wiki) %> |
<%= link_to 'Back', wikis_path %>